# Generated by Django 3.2.16 on 2023-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
