# Generated by Django 3.2.16 on 2023-02-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_teacher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_code',
        ),
    ]
