# Generated by Django 3.2.16 on 2023-02-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('join_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
